spring.application.name=crud-app
spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=pixelstudent
spring.datasource.password=parolapixel
#opresc asifasare bannerul-ui
spring.main.banner-mode=off
#reducerea logging level , warn nu va arata si erorile
logging.level.root=warn
#logging configs ca sa ne logam la SQL statement
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
# config jpa/hibernate pentru crearea automata a tabelelor.... din create in update pentru ca alicatia sa nu stearga datele anterioare
spring.jpa.hibernate.ddl-auto=update
